apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tour-of-heroes-web
  name: tour-of-heroes-web
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tour-of-heroes-web
  template:
    metadata:
      labels:
        app: tour-of-heroes-web
    spec:
      containers:
      - image: ghcr.io/0gis0/tour-of-heroes-angular:main
        imagePullPolicy: Always
        name: tour-of-heroes-web
        env:
          - name: API_URL
            value: http://20.54.216.159/api/hero
        ports:
        - containerPort: 5000
          name: web
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi" 