apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tour-of-heroes-web-with-pics
  name: tour-of-heroes-web-with-pics
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tour-of-heroes-web-with-pics
  template:
    metadata:
      labels:
        app: tour-of-heroes-web-with-pics
    spec:
      containers:
      - image: ghcr.io/0gis0/tour-of-heroes-angular:heroes-with-pics
        name: tour-of-heroes-web
        env:
          - name: API_URL
            value: http://20.54.216.159/api/hero
        ports:
        - containerPort: 5000
          name: web