apiVersion: v1
kind: Service
metadata:
  labels:
    app: tour-of-heroes-web-with-pics
  name: tour-of-heroes-web-with-pics
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: tour-of-heroes-web-with-pics